# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Hypenotic
tagline:          The Jekyll Butler
url:              http://getpoole.com
paginate:         1
baseurl:         http://localhost:4000
#baseurl: 		  http://hypenotic.github.io
author:					
  name:           Mark Otto
  url:            https://twitter.com/mdo
  email:          lionel@hypenotic.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
