# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
#permalink:        pretty
permalink:        /:categories/:title


# Setup
title:            Hypenotic
tagline:          The Jekyll Butler
url:              http://hypenotic.github.io
paginate:         10
paginate_path: "/articles/page:num"
#baseurl:         http://localhost:4000
#baseurl: 		  http://hypenotic.github.io
author:					
  name:           Mark Otto
  url:            https://twitter.com/mdo
  email:          lionel@hypenotic.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole


data_source: ./_data